apiVersion: apps/v1
kind: Deployment
metadata:
  name: kmlbroker-deployment
  namespace: kmlbroker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kmlbroker
  template:
    metadata:
      labels:
        app: kmlbroker
    spec:
      containers:
        - name: kmlbroker
          image: nrt.ocir.io/nr7audjfcmkp/kmlbroker:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
            limits:
              memory: "4Gi"
              cpu: "2"
      imagePullSecrets:
        - name: kmlbroker
---
apiVersion: v1
kind: Service
metadata:
  name: kmlbroker-svc
  namespace: kmlbroker
spec:
  type: ClusterIP  
  ports:
    - port: 3003  
      targetPort: 3003
  selector:
    app: kmlbroker
