name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - uses: actions/checkout@v4
    - name: Build Frontend Docker image
      run: docker build . --file ./frontend/Dockerfile --tag ml-brokerage-frontend:$(date +%s)
    - name: Build Backend Docker image
      run: docker build . --file ./backend/Dockerfile --tag ml-brokerage-backend:$(date +%s)
