name: Docker Image CI with GHCR

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Set npm registry
      run: npm config set registry https://registry.npmjs.org/

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Frontend Docker image
      run: docker build ./frontend --file ./frontend/Dockerfile --tag frontend-temp:${{ github.sha }}

    - name: Tag Frontend Docker image
      run: |
        docker tag frontend-temp:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/ml-brokerage-frontend:${{ github.sha }}
        docker tag frontend-temp:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/ml-brokerage-frontend:latest

    - name: Push Frontend Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/ml-brokerage-frontend:${{ github.sha }}
        docker push ghcr.io/${{ github.repository_owner }}/ml-brokerage-frontend:latest

    - name: Build Backend Docker image
      run: docker build ./backend --file ./backend/Dockerfile --tag backend-temp:${{ github.sha }}

    - name: Tag Backend Docker image
      run: |
        docker tag backend-temp:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/ml-brokerage-backend:${{ github.sha }}
        docker tag backend-temp:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/ml-brokerage-backend:latest

    - name: Push Backend Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/ml-brokerage-backend:${{ github.sha }}
        docker push ghcr.io/${{ github.repository_owner }}/ml-brokerage-backend:latest
